### ISSUE TITLE
Inefficient use of NSDateFormatter

### ISSUE THREAD

**Issue by tomassliz** [akosma/SwiftMoment#1]
Instantiate NSDateFormatter is expensive operation and you use it exactly that way. You can read this in [Apple documentation](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW1):

> Creating a date formatter is not a cheap operation. If you are likely to use a formatter frequently, it is typically more efficient to cache a single instance than to create and dispose of multiple instances. One approach is to use a static variable.

**Comment by akosma** [comment]
Pull requests are also welcome :)

**Comment by MHaroonBaig** [comment]
@tomassliz Should I send the pull request if you don't mind, using the issue that you've pointed out here ?
@akosma As of iOS7, Apple has made some expensive operations (like NSDateFormatter etc) Thread Safe but still, the experience of the fellow developers suggest that either we should go for a singleton or some caching mechanism to use those resource hungry objects. 
I was having the same issues here https://github.com/MHaroonBaig/MotionKit so I had to initialise and release the resources in time.

**Comment by MHaroonBaig** [comment]
Update: Gone through one of the Pending pull requests and understood the problem and imitations. Its not that simple as I though of. I hope there could be any workarounds.

**Comment by akosma** [comment]
@MHaroonBaig thanks a lot for your input! I'm going to see how to solve this issue soon.
