### ISSUE TITLE
"Time from now" is implement yet?

### ISSUE THREAD

**Issue by katopz** [akosma/SwiftMoment#16]
refer to http://momentjs.com/docs/#/displaying/fromnow/
I can't find something like that, is it exist somewhere?

Thanks

**Comment by akosma** [comment]
not yet, at least.

**Comment by oscar608** [comment]
is it exist now?

**Comment by katopz** [comment]
@chelsh try https://github.com/mattt/FormatterKit

**Comment by oscar608** [comment]
https://github.com/mattt/FormatterKit  this can use in swift? @katopz

**Comment by katopz** [comment]
@chelsh yes, you can use any obj-c via swift and yes i also use it.

**Comment by oscar608** [comment]
to achieve “ from now” ,you use which function  in  FormatterKit library?

**Comment by katopz** [comment]
@chelsh I use `TTTTimeIntervalFormatter`, example is on first page there.
