### ISSUE TITLE
Formatting time

### ISSUE THREAD

**Issue by staticdreams** [akosma/SwiftMoment#21]
I got a timestamp which I wrapper in `Duration` object

`var duration = Duration(value: waitingTimeMillis / 1000)`

This produces a valid result like `41:00` or `1:41:59`. Now I want to be able to format this into something more pleasant and simple like `41'` or `1h 41'`. 

How would I do that?

**Comment by akosma** [comment]
For the moment, the only possible solution would be to write your own function that takes `Duration` instances and returns `String` values.
