### ISSUE TITLE
Time format string with GMT doesn't work

### ISSUE THREAD

**Issue by hyeonjae** [akosma/SwiftMoment#30]
Below testcase fails

``` swift
func testTimeWithGMT() {
    let gmt = moment("2015-09-30T19:32:25+09:00")
    XCTAssertNotNil(gmt, "GMT String should not be nil")
}
```

**Comment by andrewbranch** [comment]
Looks like a fix for this was merged into master 2 months ago. Are we going to get a CocoaPods release? If the releases data for this repo is correct, there hasn’t been a release since January.

**Comment by akosma** [comment]
Indeed this is fixed. CocoaPods update coming soon.
