### ISSUE TITLE
support for Calendar Time

### ISSUE THREAD

**Issue by raulastu** [akosma/SwiftMoment#36]
Will it be included ?

moment().subtract(10, 'days').calendar(); // 11/17/2015
moment().subtract(6, 'days').calendar();  // Last Saturday at 6:18 PM
moment().subtract(3, 'days').calendar();  // Last Tuesday at 6:18 PM
moment().subtract(1, 'days').calendar();  // Yesterday at 6:18 PM
moment().calendar();                      // Today at 6:18 PM
moment().add(1, 'days').calendar();       // Tomorrow at 6:18 PM
moment().add(3, 'days').calendar();       // Monday at 6:18 PM
moment().add(10, 'days').calendar();      // 12/07/2015

http://momentjs.com/

**Comment by akosma** [comment]
It is not in the roadmap, although I'd be glad to add it.

**Comment by amg1976** [comment]
Yes, that would be a nice feature.
