### ISSUE TITLE
Unit tests are time zone specific

### ISSUE THREAD

**Issue by getaaron** [akosma/SwiftMoment#4]
`testCanCreateWeirdDateFromComponents()` and `testFormatDates()` fail if run in Chicago, IL because the expected result is time zone-specfic. This is because `NSDateFormatter` uses the local time zone.

**Comment by masters3d** [comment]
testCanCreateWeirdDateFromComponents()  and testFormatDates()  are also failing for PST on mine

**Comment by akosma** [comment]
I think that the pull request sent by @larcus94 fixes this. Please let me know if that is not the case. Thanks!

**Comment by akosma** [comment]
I'm closing this issue since no other reports have been made since March.

**Comment by amg1976** [comment]
Sorry, didn't saw this issue. I have the same problem with the latest version, running from Dublin, Ireland. On my pull request, I suggest a fix to it.

**Comment by akosma** [comment]
Aha! Good then, I'm checking that right now. Thanks for the tip.

**Comment by akosma** [comment]
Please let me know if #27 solved this problem.

**Comment by guzhenhuaGitHub** [comment]
testCanCreateWeirdDateFromComponents failed in Shanghai
```
XCTAssertEqual failed: ("2015440-08-31 09:08:21 GMT+01:00") is not equal to ("2015440-02-13 12:57:11 GMT+01:00") - The date is weird...!
```
