### ISSUE TITLE
Release latest version to Cocoapods with public date and timezone

### ISSUE THREAD

**Issue by AndrewBarba** [akosma/SwiftMoment#43]
Can we update the version and get the latest version out to Cocoapods?

**Comment by akosma** [comment]
I'll try to get that done this weekend. Thanks!

**Comment by AndrewBarba** [comment]
Thank you! I really appreciate it

**Comment by AndrewBarba** [comment]
Hey any updates on this?

**Comment by akosma** [comment]
With apologies for the delay, tagged and pushed to Cocoapods. Thanks for the PR!
