### ISSUE TITLE
Function Moment.add(value: Int, _ unit: TimeUnit) -> Moment goes wrong.

### ISSUE THREAD

**Issue by asfara** [akosma/SwiftMoment#48]
Line 413 in Moment.swift will cause unexpected result.

```
cal.timeZone = NSTimeZone(abbreviation: "UTC")!
```

For example:

I have a date: "2016-07-01 00:00:00 GMT+08:00", then I called date.add(1, .Months), I expect to get "2016-08-01 00:00:00 GMT+08:00", but I only got "2016-07-30 16:00:00 GMT+00:00", which is "2016-07-31 00:00:00 GMT+08:00". You just convert my original date to "2016-06-30 16:00:00 GMT+00:00", then add a month. Bang! 

I modified this line as below:

```
cal.timeZone = timeZone
cal.locale = locale
```

Then it went right, but I don't know is there any other errors it would cause.

**Comment by akosma** [comment]
Thanks for reporting! I'm on it.

**Comment by akosma** [comment]
Fixed! Thanks a lot for the submission. I've added a test to verify your situation, let me know if you have more problems.

**Comment by fpillet** [comment]
Ok so the optimizations I made are very effective, but the side effect is that this issue resurfaced. If I use the technique you describe of setting the correct timezone / locale on Gregorian Calendar, it fixes it but another test fails. I'm trying to figure out what the hell is going on internally in NSCalendar.

**Comment by fpillet** [comment]
Just FYI, optimizations I made in the Swift 3 branch don't break the fix. The ones in the Swift 2 branch may have been a little too aggressive

**Comment by fpillet** [comment]
I decided not to commit the Swift 2 optimizations to the main repo, we can close this issue. All tests pass just fine with the Swift 3 speedup.
