### ISSUE TITLE
Minute function only returns a single digit + Additional Helpful Variables

### ISSUE THREAD

**Issue by cyrilzakka** [akosma/SwiftMoment#49]
If the time is 12:00 for example, the minute only returns a single digit.
In order to get around it, I did the following: 
`String(format: "%02d", startDate!.minute)`

Also, idk if you'd like me to submit a pull request, but here are a few useful variables I added for 12hour support:

```
public var twelveHour: Int {
        if hour > 12 && hour != 24 {
            return hour - 12
        } else {
            return hour
        }
    }
```

```
public var twelveHourPeriod: String {
        var period = String()
        if hour >= 12 && hour != 24 {
            period = "PM"
        } else if hour < 12 || hour == 24{
            period = "AM"
        }
        return period
    }
```

**Comment by akosma** [comment]
I'm always open to pull requests. Feel free to send me one with your modifications, and make sure you add the required tests for it (I do not accept PRs without tests or with failing tests).
