### ISSUE TITLE
fromNow() returning ""

### ISSUE THREAD

**Issue by akabab** [akosma/SwiftMoment#56]
This part is messing around

```
    private func NSDateTimeAgoLocalizedStrings(key: String) -> String {
      // get framework bundle
      let bundleIdentifier = "com.akosma.SwiftMoment"
      guard let frameworkBundle = NSBundle(identifier: bundleIdentifier) else {
        return "" <<----
      }
```

PS: I'm using pods

**Comment by akosma** [comment]
Hey @madhavajay maybe you could help me here?

**Comment by madhavajay** [comment]
Hrm.... ill take a look in the morning. Might be because Cocoapods is including the source in your project workspace therefore changing the bundle identifier, I only tested Carthage which builds it as a framework, sorry about that.

**Comment by andrekampert** [comment]
Worked for me, thanks!

**Comment by madhavajay** [comment]
Bitte schön!

**Comment by akosma** [comment]
Should be fixed through #57, will be pushed as v0.5.1 in a few minutes.

**Comment by akabab** [comment]
Thanks! working for me as well

**Comment by akosma** [comment]
Thanks @akabab for pointing this issue out and to @madhavajay for such a quick fix! 👍
