### ISSUE TITLE
weekday definition differ from moment.js

### ISSUE THREAD

**Issue by qgliu** [akosma/SwiftMoment#66]
I found the weekday is defined as Sunday 1, Monday 2 ... instead of Sunday 0, Monday 1, etc.

Could someone confirm this?

**Comment by akosma** [comment]
This is by design, as this library wraps data types found in the Cocoa Foundation framework. This library takes inspiration in moment.js, but does not aim to provide exactly the same interface or behavior.

**Comment by qgliu** [comment]
it's great to know. thanks!
