### ISSUE TITLE
Swift 2.3 compatibility

### ISSUE THREAD

**Issue by momamene** [akosma/SwiftMoment#68]
It is needed to support swift 2.3 and I found out that just replacing codes in [MomentFromNow.swift#104](https://github.com/akosma/SwiftMoment/blob/a7e123d9a4d66ce9a2c084d97c8d2f0140eb496b/SwiftMoment/SwiftMoment/MomentFromNow.swift#L104) to 

```
#if swift(>=2.3)
  let path = NSURL(fileURLWithPath:resourcePath).URLByAppendingPathComponent(bundleName)!
#else
  let path = NSURL(fileURLWithPath:resourcePath).URLByAppendingPathComponent(bundleName)
#endif
```

makes XCode 8 build fine.

So i'm ready for pulling request.

Which is better?
1. Support both version (swift2.2 and swift2.3) in `master` branch using `#ifswift` like above.
2. Make another branch `swift2.3` and split build environment into Xcode 7 and Xcode 8

**Comment by studioofthemonth** [comment]
I prefer libraries to do the second option, even if this is just a one line change. @momamene do you have a fork you're using now?

**Comment by momamene** [comment]
Yes. Check my folk. 
https://github.com/momamene/SwiftMoment/tree/swift2.3

Just appending `!` make build success in swift2.3 environment.

**Comment by akosma** [comment]
I've updated the library to use Swift 3 exclusively.
