### ISSUE TITLE
Swift 3 compatibility?

### ISSUE THREAD

**Issue by plastus** [akosma/SwiftMoment#70]
Has anyone tried using this framework in a Swift 3 project? Does it auto-convert without issues?

**Comment by grahammccarthy** [comment]
I'm using this fork for now, until It is supported:

```
pod 'SwiftMoment', :git => 'https://github.com/madhavajay/SwiftMoment.git', :branch => 'swift-3'
```

**Comment by qgliu** [comment]
any timeline to merge the swift-3 branch to master?

**Comment by phucnd0604** [comment]
@grahammccarthy it say cannot find the git

**Comment by grahammccarthy** [comment]
Hmm... 
This line is directly pulled from my podfile and I was just able to pull it down.

```
pod 'SwiftMoment', :git => 'https://github.com/madhavajay/SwiftMoment.git', :branch => 'swift-3'
```

Here is the link directly to that branch where you can grab the code manually:  https://github.com/madhavajay/SwiftMoment/tree/swift-3

I don't know if/when @akosma will get around to updating this repo.

**Comment by keith-kurak** [comment]
I can't tell what causes this, but when downloading @madhavajay's fork via cocoapods, the bundle identifier becomes "org.cocoapods.${PRODUCT_NAME:rfc1034identifier}" (effectively org.cocoapods.SwiftMoment). On MomentFromNow.swift:89, it tries to load bundle "com.akosma.SwiftMoment" and fails, thus returning empty string for any Moment.fromNow() calls.
In Xcode, I changed the beginning of the bundle identifier to "com.akosma" and then it worked again.

That org.cocoapods isn't in the source itself, so it seems like Cocoapods adds that.

**Comment by akosma** [comment]
Just updated the library to use Swift 3 exclusively.
