### ISSUE TITLE
DD format brings 33rd, made my entire app crash. 

### ISSUE THREAD

**Issue by apsoftware123** [akosma/SwiftMoment#84]
Fixed it by using dd, just in case anyone is experiencing this.

**Comment by keith-kurak** [comment]
I can second this one. DD is supposed to return padded day of month, dd is supposed to return "Su", "Mo", etc. at least according to the Moment JS docs at https://momentjs.com/docs/#/displaying/. Instead DD return the day of the year (e.g., 12/31 is 365 and dd does the day of the month).

Seems like this behavior actually matches the formatting strings used by NSDateFormatter (https://www.nsdateformatter.com). Wondering if this is the case for all formatting strings. Before this, I never had a case where the formatting string didn't do what I expected based on Moment.js docs. I'm guessing it'd be a big challenge to make it working like the JS formatting, assuming everything is fed through NSDateFormatter. In that case, probably worth just clarifying in the docs that SwiftMoment strays from the Moment JS docs when it comes to formatting strings.

**Comment by akosma** [comment]
This case is already specified in the readme. Also, this library is "inspired" by Moment JS; not a rewrite in Swift. All date formatting is delegated to an NSDateFormatter instance.
